version: '3'
services:
    local-linux:
        image: naokicpp/simu_mate:latest
        container_name: simu_mate_cont
        tty: true
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
            - 8888:8888
