name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: |
        if [ "${{ github.event_name }}" = 'release' ]; then
          export TAG_NAME="${{ github.event.release.tag_name }}"
        else
          export TAG_NAME="latest"
        fi
        echo "::set-env name=HUB_TAG::${DOCKER_HUB_BASE_NAME}:${TAG_NAME}"
    
    - name: build image
      run: |
        docker build . -t "${HUB_TAG}"

    - name: Login to Registries
      if: github.event_name != 'pull_request'
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      run: |
        echo "${DOCKER_HUB_TOKEN}" | docker login -u ${DOCKER_USERNAME} --password-stdin
